apiVersion: 1

datasources:
  - name: RAG Postgres
    uid: rag-postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: false
    url: db:5432
    user: raguser
    secureJsonData:
      password: ragpass
    jsonData:
      database: ragdb
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
